version: '{build}'
image: Visual Studio 2017

artifacts:
- path: SerilogWeb.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: LDHWXdL5WAF7TBoy3Uqc8F/5vMsxrueba2U/GbL1Io6z3JtREljb6WOFqKsFGmdR
  skip_symbols: true
  on:
    branch: master
